"""initial_schema

Revision ID: a9879be756a1
Revises: 
Create Date: 2026-02-15 23:08:24.305096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9879be756a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal', 'fecha_ingreso')
    op.drop_column('personal', 'departamento')
    op.drop_column('personal', 'dias_trabajo')
    op.drop_column('personal', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal', sa.Column('email', sa.VARCHAR(length=255), nullable=True))
    op.add_column('personal', sa.Column('dias_trabajo', sa.VARCHAR(length=50), server_default=sa.text("'Lunes,Martes,Miércoles,Jueves,Viernes'"), nullable=True))
    op.add_column('personal', sa.Column('departamento', sa.VARCHAR(length=100), nullable=True))
    op.add_column('personal', sa.Column('fecha_ingreso', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
